default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      json_key: 'playstore_key.json',
      package_name: 'com.powerlens'
    )
  end
end
