default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'playstore_key.json',
      package_name: 'com.powerlens',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
